Xuanwo/backon

.github/FUNDING.yml
.github/actions/check/action.yml
.github/dependabot.yml
.github/workflows/ci.yml
src/constant.rs
src/retry.rs

Signed-off-by: Xuanwo <github@xuanwo.io>

ci: Add github actions for CI

---

src/lib.rs
src/retry.rs

Rename `with_error_fn` into `when`.
Closes #11

refactor: rename `with_error_fn` into `when`

---

src/backoff.rs
src/constant.rs
src/exponential.rs

Signed-off-by: Xuanwo <github@xuanwo.io>

feat: Add more trait bound for backoff trait

---

src/backoff.rs
src/constant.rs
src/exponential.rs

Signed-off-by: Xuanwo <github@xuanwo.io>

feat: Allow clone on backoff builder

---

examples/async.rs
examples/blocking.rs

Add examples

---

examples/closure.rs

This example helps to understand how to use closure with `backon` and work with some input.
Related to #42

Add closure example

---

Cargo.toml
src/constant.rs
src/exponential.rs
src/retry.rs

- add jitter to `ConstantBackoff`
- change `rand` to `fastrand`
- change `futures` to `futures-core`
Fix #37

Add jitter to constant backoff

---

src/exponential.rs

1. fix the bug https://github.com/Xuanwo/backon/issues/38 in exponential strategy
2. revise the logic about 'max_delay is None' scenario

fix: revise the logic of exponential strategy

---

examples/async.rs
examples/blocking.rs
examples/closure.rs
src/retry.rs

This PR is based on my own developer experience, of not knowing how to make backon work with an async call that takes variable arguments. 
To avoid having duplicate examples is various places, we rather point to the documentation index page, where the main collection of examples seems to be placed. This way hopefully developers can find the examples they need to find, more easily.

Remove duplicate example, point to examples on docs index page

---

.github/workflows/ci.yml
src/lib.rs

blocking in wasm doesn't make sense but allow build them makes backon easier to use. Let's add them back.

chore: Allow build blocking in wasm32

---

backon/Cargo.toml
backon/src/lib.rs
backon/src/retry.rs
backon/src/retry_with_context.rs
backon/src/sleep.rs

Most backon users are accustomed to having a default sleep implementation, making it easy for them to upgrade to new versions like `0.5` or `1.0` without the feature enabled. For example: https://github.com/Xuanwo/backon/issues/128
Let's add default features to simplify their experience. Users who want custom implementations will not be affected.

refactor: Enable default features to avoid unexpected panic

---

backon/src/lib.rs
backon/src/retry.rs
backon/src/retry_with_context.rs
backon/src/sleep.rs

- Makes compilation to fail when using `DefaultSleeper` with no features enabled.
- Should not panic as it is a valid `Sleeper` is guaranteed at compile time.
- docs to instruct users to enable a feature or provide custom `Sleeper`.
Close https://github.com/Xuanwo/backon/issues/128

fix: compile to fail when using DefaultSleeper with no features enabled

---

backon/src/backoff/api.rs

Signed-off-by: Xuanwo <github@xuanwo.io>

feat: Implement BackoffBuilder for Backoff itself

---

README.md
backon/src/lib.rs

Based on the [discussion](https://github.com/Xuanwo/backon/pull/131#discussion_r1743700760), mention `sleep()` in the blocking retry examples.
Added to examples in both `README.md` and `lib.rs`.

docs: mention sleep() in blocking retry examples

---

backon/src/backoff/constant.rs
backon/src/backoff/exponential.rs
backon/src/backoff/fibonacci.rs

Hello,
Fix issue #158 by adding `without_max_delay` and `without_max_times` to **fibonacci** and **exponential** backoffs.
Also added `without_max_times` for **constant** backoff.

feat: builder_without_max_(times|delay)

---

backon/Cargo.toml

Sorry for nitpicking, I was wondering what the question marks mean in the feature deps and after learning about their meaning it occured to me that they are actually not necessary here, since the tokio respectively gloo-timers crate is added as a dependency in the same feature. Hope I understood it correctly, happy to learn more about this syntax.

chore: Remove unnecessary optional feature selectors

---

backon/Cargo.toml
backon/src/backoff/constant.rs
backon/src/backoff/exponential.rs
backon/src/backoff/fibonacci.rs
backon/src/backoff/mod.rs
backon/src/blocking_retry.rs
backon/src/blocking_retry_with_context.rs
backon/src/lib.rs
backon/src/retry.rs
backon/src/retry_with_context.rs
backon/src/sleep.rs

Split https://github.com/Xuanwo/backon/pull/168 into two PRs as requested, this is the one for no_std support.

feat: Add std support for no-std without global rand seed

---

backon/Cargo.toml
backon/src/lib.rs
backon/src/sleep.rs

This PR adds the new `FuturesTimerSleep` implementation of a `Sleeper` which is based on the https://docs.rs/futures-timer/latest/futures_timer/ crate.
This timer is runtime agnostic and also works in WASM environments and is gated via `futures-timer-sleep` feature (enabled per default).
Closes https://github.com/Xuanwo/backon/issues/153

feat: add Sleeper based on `futures-timer`

---

backon/src/backoff/constant.rs
backon/src/backoff/exponential.rs
backon/src/backoff/fibonacci.rs

Hello thank you for your work. 
I have made changes so that all builders are now const. They should still be 100% backwards compadible. I had to introduce a constructor, new, as Default cannot be const just yet.
This allows me to define a const builder at the top and use it like this:
```
const BACKOFF_BUILDER: ExponentialBuilder = ExponentialBuilder::new().with_min_delay(Duration::from_millis(1));
fn test() {
my_fn().retry(BACKOFF_BUILDER).call();
}
```
All changes:
- Refactored all methods inside FibonacciBuilder, ExponentialBuilder, and ConstantBuilder to be const.
- Added a new const `new` constructor for each builder which uses the values from default()
- Updated the default method to call `new()`.
- Added unit tests for the const builders to ensure they have the correct values.

feat: Mark builders to be const

---

backon/src/backoff/exponential.rs
backon/src/backoff/fibonacci.rs

Currently in exponential and fibonacci the jitter adds a value between 0 and min_delay, which might be very small when compared to the end of the max_delay. So when reaching max_delay, and when many different endpoints use the backoff algorithm, they will hit the backends in waves
This changes it to range from 0 to current_delay, so the jitter is always a relevant size compared to the delays.
If you prefer this to be a different parameter, let me know an I will adjust.

jitter: Make jitter range to current_delay instead of min_delay

---

backon/src/docs/examples/mod.rs
backon/src/docs/examples/retry_after.md
backon/src/retry.rs

- Close https://github.com/Xuanwo/backon/issues/63
- Close https://github.com/Xuanwo/backon/issues/150
Demo:
```rust
use core::time::Duration;
use std::error::Error;
use std::fmt::Display;
use std::fmt::Formatter;
use anyhow::Result;
use backon::ExponentialBuilder;
use backon::Retryable;
use reqwest::header::HeaderMap;
use reqwest::StatusCode;
#[derive(Debug)]
struct HttpError {
headers: HeaderMap,
}
impl Display for HttpError {
fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
write!(f, "http error")
}
}
impl Error for HttpError {}
async fn fetch() -> Result<String> {
let resp = reqwest::get("https://www.rust-lang.org").await?;
if resp.status() != StatusCode::OK {
let source = HttpError {
headers: resp.headers().clone(),
};
return Err(anyhow::Error::new(source));
} …
```

feat: Add adjust support for Retry
